### ISSUE TITLE
fails to run command taken from Arc onbarding script

### ISSUE THREAD

**Issue by nbsdpease** [Azure/ArcEnabledServersGroupPolicy#45]
When trying to onboard some on prem machines I am running into an issue with the DeployGPO powershell script.  It fails at the tags portion because we don't want to onboard these as SQL instances.

C:\installs\DeployGPO.ps1 : Cannot process argument transformation on parameter 'Tags'. Cannot convert the 
"ArcSQLServerExtensionDeployment=Disabled" value of type "System.String" to type "System.Collections.Hashtable".
At C:\installs\WindowsOnboardingScriptGPOadd.ps1:4 char:378
+ ... 086-9878-29a561ddc360  -Tags ArcSQLServerExtensionDeployment=Disabled
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [DeployGPO.ps1], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,DeployGPO.ps1

**Comment by hhcrayon** [comment]
I got the same error and solved it with the following change:

-Tags @{ArcSQLServerExtensionDeployment="Disabled"}

**Comment by nbsdpease** [comment]
Thank you for the update, that worked for me as well.
