### ISSUE TITLE
--private-link-scope

### ISSUE THREAD

**Issue by M-R-Keys** [Azure/ArcEnabledServersGroupPolicy#7]
Would it be possible to add a switch that would include a private link scope during the connection process? When generating the script in the portal there is a switch that specifies the private link scope: --private-link-scope "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/RG/providers/Microsoft.HybridCompute/privateLinkScopes/PLS

**Comment by justinytchen** [comment]
We added support for private link in the last release
